name: MAURO'S
title: MAURO'S

description: OpenStack | Ceph | Kubernetes | Linux | Code | Random 
url: 'http://mauroseb.github.io'
baseurl: '/'

author: Mauro Oddi
github_username:  mauroseb
linkedin_username:  mauro27

# Build settings
paginate: 10
permalink: /blog/:year/:month/:day/:title
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false

plugins:
- 'jekyll-paginate'
- 'jekyll-seo-tag'
- 'jekyll-feed'
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png', 'templates', 'vendor']

#theme: jekyll-theme-hacker
